### PR TITLE
Remove references to 1.22 deprecated apis in generic-app

### PR DESCRIPTION
**Pull request by Smirl**
# Summary

This should cover all of the deprecated APIs for 1.22 as per this doc
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/#priorityclass-v122

### CODE REVIEW

**Comment by Smirl** [comment]
Looks like I will need to update the github actions workflow to use a newer version of helm (for both helm 2 and 3). However, the github action you use for chart linting has had a major change too so might be a little more involved. I will look at this later today.

**Comment by mvisonneau** [comment]
😮 thanks a lot for looking into this @Smirl 🙇 !

**Comment by Smirl** [comment]
@mvisonneau I'm having a hard time here. I have got the latest actions to sort of work for the helm 3 step, but fails parsing the image (which is empty in the default values) so not sure how this worked before.

For helm 2 it fails at `ct list-changed` which I'm not sure why. This step works fine in the helm3 job. Could you take a look as I am probably missing something. I just wanted to do a 1 line helm chart change :P

**Comment by mvisonneau** [comment]
Thanks a lot for all these improvements for the chart & the CI, I will look into fixing the remaining tests!

**Pull request merged**
